In [1]:
import numpy as np 

 2D array \
    - Introduction \
    - reshape() \
    - flatten() vs ravel() \
    - indexing and slicing \
    - axis = 1 vs axis = 0 
   - dot product
- cross product
- linalg module
- 3D array and images

### items of the same type and size
### changes made in one ndarray may be visible in another. That is, an ndarray can be a “view” to another ndarray

An instance of class ndarray consists of a contiguous one-dimensional segment of computer memory (owned by the array, or by some other object), combined with an indexing scheme that maps N integers into the location of an item in the block. 

- An array is considered aligned if the memory offsets for all elements and the base offset itself is a multiple of self.itemsize.

In [9]:
x = np.arange(3, 27,2)
x.shape , x 

((12,), array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25]))

In [17]:
# numpy.reshape(a, newshape, order='C')
# think of reshape as 1) flattening the input array and 
# 2) inserting each element into the output array with new shape.
# elements are selected in row-major order 
x = x.reshape(2,6)
x, x.reshape(6,2), x.reshape(3,4), x.reshape(4,3), x.reshape(12)   

(array([[ 3,  5,  7,  9, 11, 13],
        [15, 17, 19, 21, 23, 25]]),
 array([[ 3,  5],
        [ 7,  9],
        [11, 13],
        [15, 17],
        [19, 21],
        [23, 25]]),
 array([[ 3,  5,  7,  9],
        [11, 13, 15, 17],
        [19, 21, 23, 25]]),
 array([[ 3,  5,  7],
        [ 9, 11, 13],
        [15, 17, 19],
        [21, 23, 25]]),
 array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25]))

In [19]:
x.flags, x.strides 

(  C_CONTIGUOUS : True
   F_CONTIGUOUS : False
   OWNDATA : False
   WRITEABLE : True
   ALIGNED : True
   WRITEBACKIFCOPY : False,
 (24, 4))

In [35]:
# np.ndarray.reshape
print(x) 
print(x.reshape(3,4))
print(x.reshape((3,4), order='F'))

# np.reshape(arr) 
print('\n\nC\n') 
print(np.reshape(x, (3,4), order = 'C'))

print('\nF\n') 
# R/W as Fortran like index order 
print(np.reshape(x, (3,4), order = 'F'))

print('\nA \n') 
# in Fortran-like index order,, if a is Fortran contiguous in memory, C-like order otherwise
print(np.reshape(x, (3,4), order = 'A'))

[[ 3  5  7  9 11 13]
 [15 17 19 21 23 25]]
[[ 3  5  7  9]
 [11 13 15 17]
 [19 21 23 25]]
[[ 3 17  9 23]
 [15  7 21 13]
 [ 5 19 11 25]]


C

[[ 3  5  7  9]
 [11 13 15 17]
 [19 21 23 25]]

F

[[ 3 17  9 23]
 [15  7 21 13]
 [ 5 19 11 25]]

A 

[[ 3  5  7  9]
 [11 13 15 17]
 [19 21 23 25]]


### flatten vs ravel 

flatten is a method of an ndarray object and hence can only be called for true numpy arrays.

ravel is a library-level function and hence can be called on any object that can successfully be parsed.

    - ravel works on list of ndarrays, flatten not available for such object 

In [48]:
# np.ravel(arr, order = 'C')
# returns a contiguous flatteend array 
# order, C, F, A 
# K for reading elements in the order they occur in the memory 
x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x), np.ravel(x, 'F'),  np.ravel(x, 'K') 

(array([1, 2, 3, 4, 5, 6]),
 array([1, 4, 2, 5, 3, 6]),
 array([1, 2, 3, 4, 5, 6]))

In [49]:
a = np.arange(12)
print(a) 
a.reshape(2,3,2),a.reshape(2,3,2).shape, a.reshape(2,3,2).swapaxes(1,2), a.reshape(2,3,2).swapaxes(1,2).shape 

[ 0  1  2  3  4  5  6  7  8  9 10 11]


(array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],
 
        [[ 6,  7],
         [ 8,  9],
         [10, 11]]]),
 (2, 3, 2),
 array([[[ 0,  2,  4],
         [ 1,  3,  5]],
 
        [[ 6,  8, 10],
         [ 7,  9, 11]]]),
 (2, 2, 3))

In [50]:
a2 = a.reshape(2,3,2).swapaxes(1,2)
a2.ravel('C'), a2.ravel('K') 

(array([ 0,  2,  4,  1,  3,  5,  6,  8, 10,  7,  9, 11]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]))

In [51]:
# flatten returns a copy of array collapsed into one dimension 
# order: C,F,A, K 
a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])

In [55]:
# flatten has no base? 
# a view means it is a copy of a base ndarray 
# flatten is a new array, so no base 
id(a), id(a.flatten()), id(a.ravel()), a.flatten().base,  a.ravel().base 

(2000367546800,
 2000387895344,
 2000387895344,
 None,
 array([[1, 2],
        [3, 4]]))

### indexing and slicing 

In [56]:
arr_2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr_2d[0, 1], arr_2d[1:3, 1:3] 

(1,
 array([[4, 5],
        [7, 8]]))

In [58]:
arr_3d = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
arr_3d[:, 0, :], arr_3d[1, 0, 0]

(array([[0, 1],
        [4, 5]]),
 4)

### axis = 1 vs axis = 0 

In [59]:
# axes are direction along rows, columns 
# 0 : along the rows, 1st axis 
# 1 : across the columns, 2nd axis 

In [60]:
np_array_2d = np.arange(0, 6).reshape([2,3])
np_array_2d

array([[0, 1, 2],
       [3, 4, 5]])

In [63]:
# axis : which axis gets collapsed, or aggregated 
np.sum(np_array_2d, axis = 0), np.sum(np_array_2d, axis = 1)

(array([3, 5, 7]), array([ 3, 12]))

In [64]:
# for np.concatenate 
# axis : axis along which we stack the arrays 
s = np.array([[1,1,1],[1,1,1]])
r = np.array([[9,9,9],[9,9,9]])
s,r 

(array([[1, 1, 1],
        [1, 1, 1]]),
 array([[9, 9, 9],
        [9, 9, 9]]))

In [66]:
np.concatenate([s, r], axis = 0), np.concatenate([s, r], axis = 1)

(array([[1, 1, 1],
        [1, 1, 1],
        [9, 9, 9],
        [9, 9, 9]]),
 array([[1, 1, 1, 9, 9, 9],
        [1, 1, 1, 9, 9, 9]]))

### Dot Product 

In [70]:
print(s.shape, r.shape) 
np.dot(s,r.T), s@r.T  

(2, 3) (2, 3)


(array([[27, 27],
        [27, 27]]),
 array([[27, 27],
        [27, 27]]))